baseurl = "https://getblank.github.io/site/"
languageCode = "en-us"
title = "BLANK cloud platform"
publishdir = "docs"

[params]
  description = "Облачная платформа для создания бэкенда с открытым исходным кодом"
  author = "BLANK"
  keywords = "BaaS, backend, cloud, iot, platform, бэкенд, облачный сервис, интернет вещей"
  locale = "ru-RU"

[taxonomies]
tag = "tags"

[[menu.doc]]
    name = "Начало работы"
    pre = "<i class='fa fa-heart'></i>"
    weight = -120
    identifier = "start"
[[menu.doc]]
    name = "Blank CLI"
    pre = "<i class='fa fa-road'></i>"
    weight = -110
    identifier = "cli"
[[menu.doc]]
    name = "Blank Schema"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    identifier = "schema"
[[menu.doc]]
    name = "Serverside JS API"
    pre = "<i class='fa fa-road'></i>"
    weight = -90
    identifier = "serverjs"
[[menu.doc]]
    name = "HTTP API"
    pre = "<i class='fa fa-road'></i>"
    weight = -80
    identifier = "httpapi"
[[menu.doc]]
    name = "Интеграция"
    pre = "<i class='fa fa-road'></i>"
    weight = -70
    identifier = "social"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4
