baseurl = "http://getblank.net/"
languageCode = "en-us"
title = "BLANK cloud platform"

[params]
  description = "Облачная платформа для создания бэкенда с открытым исходным кодом"
  author = "BLANK"
  keywords = "BaaS, backend, cloud, iot, platform, бэкенд, облачный сервис, интернет вещей"
  locale = "ru-RU"

[taxonomies]
tag = "tags"

[[menu.doc]]
    name = "Начало работы"
    pre = "<i class='fa fa-heart'></i>"
    weight = -120
    identifier = "start"
    url = "/doc/"
[[menu.doc]]
    name = "Blank CLI"
    pre = "<i class='fa fa-road'></i>"
    weight = -110
    identifier = "cli"
    url = "/doc/"
[[menu.doc]]
    name = "Blank Schema"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    identifier = "schema"
    url = "/doc/"
[[menu.doc]]
    name = "Serverside JS API"
    pre = "<i class='fa fa-road'></i>"
    weight = -90
    identifier = "serverjs"
    url = "/doc/"
[[menu.doc]]
    name = "HTTP API"
    pre = "<i class='fa fa-road'></i>"
    weight = -80
    identifier = "httpapi"
    url = "/doc/"
[[menu.doc]]
    name = "Интеграция"
    pre = "<i class='fa fa-road'></i>"
    weight = -70
    identifier = "social"
    url = "/doc/"